apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    meta.helm.sh/release-name: commerce
    meta.helm.sh/release-namespace: kyma-integration
  creationTimestamp: "2022-03-18T13:18:36Z"
  generation: 3
  labels:
    app: commerce-application-gateway
    app.kubernetes.io/instance: commerce
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: application
    helm.sh/chart: application-0.0.1
    release: commerce
  name: commerce-application-gateway
  namespace: kyma-integration
  resourceVersion: "8778"
  uid: 984311e1-50c9-4211-8bd9-dd4f898f6e73
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: commerce-application-gateway
      release: commerce
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      creationTimestamp: null
      labels:
        app: commerce-application-gateway
        release: commerce
    spec:
      containers:
      - args:
        - /applicationgateway
        - --proxyPort=8080
        - --externalAPIPort=8081
        - --application=commerce
        - --namespace=kyma-integration
        - --requestTimeout=10
        - --skipVerify=true
        - --proxyTimeout=10
        - --proxyCacheTTL=120
        - --requestLogging=false
        image: eu.gcr.io/kyma-project/application-gateway:984ed90c
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: commerce-application-gateway
        ports:
        - containerPort: 8080
          name: proxy-port
          protocol: TCP
        - containerPort: 8081
          name: http-api-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/health
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: commerce-application-gateway
      serviceAccountName: commerce-application-gateway
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-03-18T13:26:47Z"
    lastUpdateTime: "2022-03-18T13:26:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-03-18T13:18:36Z"
    lastUpdateTime: "2022-03-18T13:26:59Z"
    message: ReplicaSet "commerce-application-gateway-f54856499" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
